_target_: sqp_ann.models.DNSMOS

n_fft: 640
n_mels: 120

channels: [32, 32, 32, 64]
hidden_1: 64
hidden_2: 64
dropout: 0.3
conv_activation: relu

preproc: 
  _target_: torchaudio.transforms.MelSpectrogram
  sample_rate: ${sr}
  n_fft: ${model.n_fft}
  n_mels: ${model.n_mels}
  power: 2
  center: False
