_target_: sqp_ann.datasets.SQPDataset

audio_dir: ${oc.env:DATASETS_PATH}
metrics_file: ${oc.env:DATASETS_PATH}dns2020_sqp_testset/synthetic/no_reverb/metrics.pkl
sr: ${sr}
winlen: 5
winhop: 5
metric: "pesq"
